apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    # mylabelname: webapp
    app: webapp
    release: "0"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-release0-5
  labels:
    # mylabelname: webapp
    app: webapp
    release: "0-5"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
    # release: "0-5"
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1